language: python

python:
    - "3.0"

before_install:
    #- sudo apt-get update -q
    #- sudo apt-get install libblas-dev
    #- sudo apt-get install liblapack-dev
    #- sudo apt-get install gfortran

# Install packages
install:
    #- pip install scipy
    #- pip install numpy
    #- pip install matplotlib
    #- pip install pandas
    #- pip install python-coveralls
    #- pip install coverage
    #- pip install nose
    #- python setup.py install

script:
    #- export PYTHONIOENCODING=UTF-8
    #- nosetests --with-coverage

after_success:
  #- bash <(curl -s https://codecov.io/bash)  -g **/progressbar/*